name: Vehicle Server CI
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      
      - name: Check Node Version
        run: node --version
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build

      - name: Run Lint
        run: npm run lint

      - name: Run Test
        run: npm run test
      
      - name: List dist output
        run: ls dist/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: contains('refs/heads/main', github.ref)
        with:
          username: alliahbw
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push if on `main` branch
        if: contains('refs/heads/main', github.ref)
        run: |
          TAG="${{github.ref_name}}" npm run release